{
  inputs,
  cell,
}: let
  inherit (inputs) nixpkgs;
in {
  home.packages = with nixpkgs; [
    ripgrep
    git
    sudo
    bottom
  ];

  home.shellAliases = {
    top = "btm";
  };

  xdg.enable = true;

  programs.zsh = {
    enable = true;
    enableCompletion = true;
    dotDir = ".config/zsh";
  };

  home.file = {
    ".config/zsh" = {
      source = ./_zsh;
      recursive = true;
    };

    ".config/zsh/extra.zshenv".text = ''
    '';

    ".config/zsh/extra.zshrc".text = ''
      source ${./_zsh}/prompt.zsh
      _cache tmuxifier init -
      eval "$(direnv hook zsh)"
    '';
  };
}
# # This file was autogenerated, do not edit it!
# alias k="kubectl"
# source '/nix/store/yg00rzmcnxn0rk92pdcszskzc66y56kp-prompt.zsh'
# source '/home/jboyens/.config/dotfiles/config/tmux/aliases.zsh'
# source '/home/jboyens/.config/dotfiles/config/git/aliases.zsh'
# source '/home/jboyens/.config/dotfiles/config/docker/aliases.zsh'
# source '/home/jboyens/.config/dotfiles/config/emacs/aliases.zsh'
# _cache bw completion --shell zsh; compdef _bw bw;
# _cache tmuxifier init -
# eval "$(direnv hook zsh)"
# [ "$TERM" = alacritty ] && export TERM=xterm-256color

