# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/creack/pty";
    fetch = {
      type = "git";
      url = "https://github.com/creack/pty";
      rev = "8ab47f72e8547a066b4ea926f4523775bc1a0ec2";
      sha256 = "0hpi7an90ypmvpiiw7pjdwjl7y9c787fxgsspm0a8cl311kd9ncy";
    };
  }
  {
    goPackagePath = "github.com/kr/pty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pty";
      rev = "24b51915630e1d9d3c6adf15a3a96796bbc3cd43";
      sha256 = "1vcl6f90n0f8s8b4fyh0832ilybjqcypqyj233lqj1hx62fvgdbk";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "056763e48d71961566155f089ac0f02f1dda9b5a";
      sha256 = "0dcmns62hwid7hk4bmpl22z6ygjh168p23x3arzy320sd1lvap92";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "59c9f1ba88faf592b225274f69c5ef1e4ebacf82";
      sha256 = "014iiqjh9sikbcvacqiwhg6mvrsrr1va91wmc9yrnsm11c63yxfa";
    };
  }
]
