icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#1E2029"
idle_fg = "#F8F8F2"
info_bg = "#1E2029"
info_fg = "#F8F8F2"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
warning_bg = "#1E2029"
warning_fg = "#F0C674"
critical_bg = "#1E2029"
critical_fg = "#F0C674"
alternating_tint_bg = "#181A23"
alternating_tint_fg = "#F0C674"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp59s0"
format = "{signal_strength} {bitrate}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = " {utilization}% {frequency}GHz"

[[block]]
block = "load"
interval = 1
format = " {1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = " {percentage}% {time}"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/jboyens/.mail/flexe/INBOX", "/home/jboyens/.mail/fooninja/INBOX"]

[[block]]
block = "weather"
format = "{weather} {temp}°F"
service = { name = "openweathermap", api_key = "00000000000000000000000000000000", city_id = "5809844", units = "imperial" }

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
