[pizauth]
src.github_tag = "ltratt/pizauth"
fetch.github = "ltratt/pizauth"
cargo_locks = [ "Cargo.lock" ]

[cyrus-sasl-xoauth2]
src.github = "moriyoshi/cyrus-sasl-xoauth2"
fetch.github = "moriyoshi/cyrus-sasl-xoauth2"

[gnupg]
src.manual = "gnupg-2.4.0"
fetch.git = "https://dev.gnupg.org/source/gnupg.git"
