# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cyrus-sasl-xoauth2 = {
    pname = "cyrus-sasl-xoauth2";
    version = "v0.2";
    src = fetchFromGitHub {
      owner = "moriyoshi";
      repo = "cyrus-sasl-xoauth2";
      rev = "v0.2";
      fetchSubmodules = false;
      sha256 = "sha256-lI8uKtVxrziQ8q/Ss+QTgg1xTObZUTAzjL3MYmtwyd8=";
    };
  };
  kustomize = {
    pname = "kustomize";
    version = "kustomize/v5.1.0";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kustomize";
      rev = "kustomize/v5.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-nYndDoaCMyIvMlhHawgcv8WCCa3HYgAcF+3QxyYxub4=";
    };
  };
  pizauth = {
    pname = "pizauth";
    version = "pizauth-0.3.0";
    src = fetchFromGitHub {
      owner = "ltratt";
      repo = "pizauth";
      rev = "pizauth-0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-jqfK926KrWevsP+Yif3PdMIZWeIIQaA5jP14acZehwc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./pizauth-pizauth-0.3.0/Cargo.lock;
      outputHashes = {
      };
    };
  };
  sloth = {
    pname = "sloth";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "slok";
      repo = "sloth";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-KMVD7uH3Yg9ThnwKKzo6jom0ctFywt2vu7kNdfjiMCs=";
    };
  };
}
