# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cyrus-sasl-xoauth2 = {
    pname = "cyrus-sasl-xoauth2";
    version = "v0.2";
    src = fetchFromGitHub {
      owner = "moriyoshi";
      repo = "cyrus-sasl-xoauth2";
      rev = "v0.2";
      fetchSubmodules = false;
      sha256 = "sha256-lI8uKtVxrziQ8q/Ss+QTgg1xTObZUTAzjL3MYmtwyd8=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "d904bc05323cd2977c493531219ad6e4aefe45b5";
    src = fetchgit {
      url = "https://git.sr.ht/~dnkl/fuzzel";
      rev = "d904bc05323cd2977c493531219ad6e4aefe45b5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2lTo3FfmREFgyoTF2p9Au9FzCSmxU6LOKfSHjV/3pZM=";
    };
    date = "2023-01-02";
  };
  grizzly = {
    pname = "grizzly";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "grafana";
      repo = "grizzly";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-6z/6QZlCm4mRMKAVzLnOokv8ib7Y/7a17ojjMfeoJ4w=";
    };
  };
  kustomize = {
    pname = "kustomize";
    version = "kustomize/v5.1.1";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kustomize";
      rev = "kustomize/v5.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-XtpMws2o3h19PsRJXKg+y5/Zk3bc6mJ4O1LLZ40ioTM=";
    };
  };
  pizauth = {
    pname = "pizauth";
    version = "pizauth-0.3.0";
    src = fetchFromGitHub {
      owner = "ltratt";
      repo = "pizauth";
      rev = "pizauth-0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-jqfK926KrWevsP+Yif3PdMIZWeIIQaA5jP14acZehwc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./pizauth-pizauth-0.3.0/Cargo.lock;
      outputHashes = {
      };
    };
  };
  slack = {
    pname = "slack";
    version = "4.33.84";
    src = fetchurl {
      url = "https://downloads.slack-edge.com/releases/linux/4.33.84/prod/x64/slack-desktop-4.33.84-amd64.deb";
      sha256 = "sha256-Df6UzG1oJOeLJPUx+Ndh/gZB51aBJoROqbPn+1IdVDI=";
    };
  };
  sloth = {
    pname = "sloth";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "slok";
      repo = "sloth";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-KMVD7uH3Yg9ThnwKKzo6jom0ctFywt2vu7kNdfjiMCs=";
    };
  };
  testkube = {
    pname = "testkube";
    version = "v1.13.12";
    src = fetchFromGitHub {
      owner = "kubeshop";
      repo = "testkube";
      rev = "v1.13.12";
      fetchSubmodules = false;
      sha256 = "sha256-0bGIZUdWrodhoRXg7e1CiK0tHLVb2reltlyG3aorR0Q=";
    };
  };
  tilt = {
    pname = "tilt";
    version = "v0.33.3";
    src = fetchFromGitHub {
      owner = "tilt-dev";
      repo = "tilt";
      rev = "v0.33.3";
      fetchSubmodules = false;
      sha256 = "sha256-TNZE335tH50E96yJzD26U+JbVxjU746Wa/8YDGHFeto=";
    };
  };
}
