# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cyrus-sasl-xoauth2 = {
    pname = "cyrus-sasl-xoauth2";
    version = "v0.2";
    src = fetchFromGitHub {
      owner = "moriyoshi";
      repo = "cyrus-sasl-xoauth2";
      rev = "v0.2";
      fetchSubmodules = false;
      sha256 = "sha256-lI8uKtVxrziQ8q/Ss+QTgg1xTObZUTAzjL3MYmtwyd8=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "d904bc05323cd2977c493531219ad6e4aefe45b5";
    src = fetchgit {
      url = "https://git.sr.ht/~dnkl/fuzzel";
      rev = "d904bc05323cd2977c493531219ad6e4aefe45b5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2lTo3FfmREFgyoTF2p9Au9FzCSmxU6LOKfSHjV/3pZM=";
    };
    date = "2023-01-02";
  };
  grizzly = {
    pname = "grizzly";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "grafana";
      repo = "grizzly";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-6z/6QZlCm4mRMKAVzLnOokv8ib7Y/7a17ojjMfeoJ4w=";
    };
  };
  kustomize = {
    pname = "kustomize";
    version = "kustomize/v5.1.1";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kustomize";
      rev = "kustomize/v5.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-XtpMws2o3h19PsRJXKg+y5/Zk3bc6mJ4O1LLZ40ioTM=";
    };
  };
  pizauth = {
    pname = "pizauth";
    version = "9c2ed02861d17ec911a221c2b9b1c2edf7bcf68f";
    src = fetchFromGitHub {
      owner = "ltratt";
      repo = "pizauth";
      rev = "9c2ed02861d17ec911a221c2b9b1c2edf7bcf68f";
      fetchSubmodules = false;
      sha256 = "sha256-8wW9nf1YW9tfPuEE6JQTPeXdzrZCKP+1Zmo/B0dG38E=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./pizauth-9c2ed02861d17ec911a221c2b9b1c2edf7bcf68f/Cargo.lock;
      outputHashes = {
      };
    };
    date = "2023-08-19";
  };
  slack = {
    pname = "slack";
    version = "4.33.90";
    src = fetchurl {
      url = "https://downloads.slack-edge.com/releases/linux/4.33.90/prod/x64/slack-desktop-4.33.90-amd64.deb";
      sha256 = "sha256-VKc9H4XWXJALKXPn1zegAUnT2tN9mWD52t/wl6LoVNw=";
    };
  };
  sloth = {
    pname = "sloth";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "slok";
      repo = "sloth";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-KMVD7uH3Yg9ThnwKKzo6jom0ctFywt2vu7kNdfjiMCs=";
    };
  };
  swaync = {
    pname = "swaync";
    version = "v0.9.0";
    src = fetchFromGitHub {
      owner = "ErikReider";
      repo = "SwayNotificationCenter";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-mwwSTs4d9jUXUy33nSYJCRFlpH6naCmbRUSpfVacMBE=";
    };
  };
  testkube = {
    pname = "testkube";
    version = "v1.14.0";
    src = fetchFromGitHub {
      owner = "kubeshop";
      repo = "testkube";
      rev = "v1.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-PY7oCNV1keoZWg+95N8ZDfdBlv8v1X0yUasQwIlsVeI=";
    };
  };
  tilt = {
    pname = "tilt";
    version = "v0.33.4";
    src = fetchFromGitHub {
      owner = "tilt-dev";
      repo = "tilt";
      rev = "v0.33.4";
      fetchSubmodules = false;
      sha256 = "sha256-rQ5g5QyGyuJAHmE8zGFzqtpqW2xEju5JV386y9Cn+cs=";
    };
  };
}
