{
  inputs,
  cell,
}: let
  inherit (inputs) nixpkgs;
in {
  file = {
    ".config/tmux" = {
      source = ./_tmux;
      recursive = true;
    };
    ".config/tmux/extraInit" = {
      text = ''
        #!/usr/bin/env bash
        # This file is auto-generated by nixos, don't edit by hand!
        tmux run-shell '${nixpkgs.tmuxPlugins.copycat}/share/tmux-plugins/copycat/copycat.tmux'
        tmux run-shell '${nixpkgs.tmuxPlugins.prefix-highlight}/share/tmux-plugins/prefix-highlight/prefix_highlight.tmux'
        tmux run-shell '${nixpkgs.tmuxPlugins.yank}/share/tmux-plugins/yank/yank.tmux'
        tmux run-shell '${nixpkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/resurrect.tmux'
      '';
      executable = true;
    };
  };

  sessionPath = [
    "$TMUXIFIER/bin"
  ];
  sessionVariables = {
    TMUX_HOME = "$XDG_CONFIG_HOME/tmux";
    TMUXIFIER = "$XDG_DATA_HOME/tmuxifier";
    TMUXIFIER_LAYOUT_PATH = "$XDG_DATA_HOME/tmuxifier";
  };
}
