{
  inputs,
  cell,
}: let
  inherit (inputs) nixpkgs;
in {
  # Use a stable profile name so we can target it in themes
  xdg.configFile = {
    "tmux" = {
      source = ./_tmux;
      recursive = true;
    };
    "tmux/extraInit" = {
      text = ''
        #!/usr/bin/env bash
        # This file is auto-generated by nixos, don't edit by hand!
        tmux run-shell '${nixpkgs.tmuxPlugins.copycat}/share/tmux-plugins/copycat/copycat.tmux'
        tmux run-shell '${nixpkgs.tmuxPlugins.prefix-highlight}/share/tmux-plugins/prefix-highlight/prefix_highlight.tmux'
        tmux run-shell '${nixpkgs.tmuxPlugins.yank}/share/tmux-plugins/yank/yank.tmux'
        tmux run-shell '${nixpkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/resurrect.tmux'
      '';
      executable = true;
    };
  };

  home.sessionPath = [
    "$TMUXIFIER/bin"
  ];

  home.sessionVariables = {
    TMUX_HOME = "${config.xdg.configHome}/tmux";
    TMUXIFIER = "${config.xdg.dataHome}/tmuxifier";
    TMUXIFIER_LAYOUT_PATH = "${config.xdg.dataHome}/tmuxifier";
  };

  programs.zsh.initExtra = ''
    ### tmux aliases
    alias ta='tmux attach'
    alias tl='tmux ls'

    if [[ -n $TMUX ]]; then # From inside tmux
      alias tf='tmux find-window'
      # Detach all other clients to this session
      alias mine='tmux detach -a'
      # Send command to other tmux window
      tt() {
        tmux send-keys -t .+ C-u && \
          tmux set-buffer "$*" && \
          tmux paste-buffer -t .+ && \
          tmux send-keys -t .+ Enter;
      }
      # Create new session (from inside one)
      tn() {
        local name="''${1:-`basename $PWD`}"
        TMUX= tmux new-session -d -s "$name"
        tmux switch-client -t "$name"
        tmux display-message "Session #S created"
      }
    else # From outside tmux
      # Start grouped session so I can be in two different windows in one session
      tdup() { tmux new-session -t "''${1:-`tmux display-message -p '#S'`}"; }
    fi
    ### end tmux
  '';

  programs.tmux = {
    enable = true;
  };
}
