#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)  ;;
    arch)   yay --needed --noconfirm -S bitwarden-cli ;;
    debian) ;;
  esac
}

# update() {}

# link() {}

# clean() {}

init "$@"
