# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cyrus-sasl-xoauth2 = {
    pname = "cyrus-sasl-xoauth2";
    version = "v0.2";
    src = fetchFromGitHub {
      owner = "moriyoshi";
      repo = "cyrus-sasl-xoauth2";
      rev = "v0.2";
      fetchSubmodules = false;
      sha256 = "sha256-lI8uKtVxrziQ8q/Ss+QTgg1xTObZUTAzjL3MYmtwyd8=";
    };
  };
  fuzzel = {
    pname = "fuzzel";
    version = "d904bc05323cd2977c493531219ad6e4aefe45b5";
    src = fetchgit {
      url = "https://git.sr.ht/~dnkl/fuzzel";
      rev = "d904bc05323cd2977c493531219ad6e4aefe45b5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2lTo3FfmREFgyoTF2p9Au9FzCSmxU6LOKfSHjV/3pZM=";
    };
    date = "2023-01-02";
  };
  gnupg = {
    pname = "gnupg";
    version = "gnupg-2.4.0";
    src = fetchgit {
      url = "https://dev.gnupg.org/source/gnupg.git";
      rev = "gnupg-2.4.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YoeGeAV3qaKPUrSuWm7RTFKb5ariQR4UGYo2Bkaj3rY=";
    };
  };
  grizzly = {
    pname = "grizzly";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "grafana";
      repo = "grizzly";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-6z/6QZlCm4mRMKAVzLnOokv8ib7Y/7a17ojjMfeoJ4w=";
    };
  };
  kustomize = {
    pname = "kustomize";
    version = "kustomize/v5.2.1";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "kustomize";
      rev = "kustomize/v5.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-NuDg9Vtfxddosi8J7p6+WI2jDM2k16gbWsQcZF27vJo=";
    };
  };
  pizauth = {
    pname = "pizauth";
    version = "pizauth-1.0.2";
    src = fetchFromGitHub {
      owner = "ltratt";
      repo = "pizauth";
      rev = "pizauth-1.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-mRUN/e3Zh2HzMyZfSt0qb5eY5QJO/I+LTOuhszBunNk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./pizauth-pizauth-1.0.2/Cargo.lock;
      outputHashes = {
      };
    };
  };
  slack = {
    pname = "slack";
    version = "4.34.121";
    src = fetchurl {
      url = "https://downloads.slack-edge.com/releases/linux/4.34.121/prod/x64/slack-desktop-4.34.121-amd64.deb";
      sha256 = "sha256-5e+GwVTnhZ4/+NyeIN/35onbg6GqTNoX+BXec3VLKYQ=";
    };
  };
  sloth = {
    pname = "sloth";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "slok";
      repo = "sloth";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-KMVD7uH3Yg9ThnwKKzo6jom0ctFywt2vu7kNdfjiMCs=";
    };
  };
  swaync = {
    pname = "swaync";
    version = "v0.9.0";
    src = fetchFromGitHub {
      owner = "ErikReider";
      repo = "SwayNotificationCenter";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-mwwSTs4d9jUXUy33nSYJCRFlpH6naCmbRUSpfVacMBE=";
    };
  };
  testkube = {
    pname = "testkube";
    version = "v1.15.9";
    src = fetchFromGitHub {
      owner = "kubeshop";
      repo = "testkube";
      rev = "v1.15.9";
      fetchSubmodules = false;
      sha256 = "sha256-0o8upbC1Hte4nHrCEqpGYSVxUO/c1RvOIYWGwZP0XTQ=";
    };
  };
  tilt = {
    pname = "tilt";
    version = "v0.33.6";
    src = fetchFromGitHub {
      owner = "tilt-dev";
      repo = "tilt";
      rev = "v0.33.6";
      fetchSubmodules = false;
      sha256 = "sha256-WtE8ExUKFRtdYeg0+My/DB+L/qT+J1EaKHKChNjC5oI=";
    };
  };
}
