#!/bin/bash
DOTS=~/.dotfiles
source $DOTS/env

# A tidy $HOME is a tidy mind
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
[[ -e ~/.Xauthority ]] && mv -f ~/.Xauthority "$XAUTHORITY"

# Check for a USB Device with the vendor 0xfeed (Ergodox EZ)
if [[ -z "$(lsusb -d 0xfeed:)" ]]
then
      setxkbmap dvorak
else
      setxkbmap us
fi

ARCH=$DOTS/base/arch-desktop
[[ -f $ARCH/Xresources ]] && xrdb    $ARCH/Xresources
[[ -f $ARCH/Xmodmap    ]] && xmodmap $ARCH/Xmodmap

~/adjust_dpi.sh

# set wallpaper
[[ -e ~/wallpaper ]] && feh --no-fehbg --image-bg black --bg-max ~/wallpaper

# Let me know
$DOTS/bin/ding startup

# autostart programs
{
  run() {
    if _is_callable "$1" && ! _is_running "$1"; then
      "$@"
    fi
  }

  # essentials
  run sxhkd &    # keyboard daemon
  run dunst &    # notifications

  # non-essentials
  {
    sleep 2
    run mpd &       # music server
    run redshift &  # screen temperature based on time-of-day
    run rslsync &   # resilio sync
    run compton &   # perdy effects + transparency

    # If sxhkd isn't running by now, something is wrong
    _is_running sxhkd || urxvt &
  } &
} 2>&1 >$XDG_DATA_HOME/xsession-errors.log
