# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cyrus-sasl-xoauth2 = {
    pname = "cyrus-sasl-xoauth2";
    version = "v0.2";
    src = fetchFromGitHub {
      owner = "moriyoshi";
      repo = "cyrus-sasl-xoauth2";
      rev = "v0.2";
      fetchSubmodules = false;
      sha256 = "sha256-lI8uKtVxrziQ8q/Ss+QTgg1xTObZUTAzjL3MYmtwyd8=";
    };
  };
  gnupg = {
    pname = "gnupg";
    version = "gnupg-2.4.0";
    src = fetchgit {
      url = "https://dev.gnupg.org/source/gnupg.git";
      rev = "gnupg-2.4.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YoeGeAV3qaKPUrSuWm7RTFKb5ariQR4UGYo2Bkaj3rY=";
    };
  };
  pizauth = {
    pname = "pizauth";
    version = "pizauth-1.0.4";
    src = fetchFromGitHub {
      owner = "ltratt";
      repo = "pizauth";
      rev = "pizauth-1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-Du+MVdYVQgH2V7928kpur+Xp/0y7HXgB8ZC0qciiQvs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./pizauth-pizauth-1.0.4/Cargo.lock;
      outputHashes = {
      };
    };
  };
}
