{
  inputs,
  cell,
}: let
  inherit (inputs) nixpkgs;
  inherit (cell) lib;
in {
  options = with lib.types; {
    aliases = lib.mkOpt (attrsOf (either str path)) {};

    rcInit = lib.mkOpt' lines "" ''
      Zsh lines to be written to $XDG_CONFIG_HOME/zsh/extra.zshrc and sourced by
      $XDG_CONFIG_HOME/zsh/.zshrc
    '';
    envInit = lib.mkOpt' lines "" ''
      Zsh lines to be written to $XDG_CONFIG_HOME/zsh/extra.zshenv and sourced
      by $XDG_CONFIG_HOME/zsh/.zshenv
    '';

    rcFiles = lib.mkOpt (listOf (either str path)) [];
    envFiles = lib.mkOpt (listOf (either str path)) [];
  };

  config = {
    home.packages = with nixpkgs; [ripgrep sudo bottom fzf exa];

    # these don't work because I'm replacing the whole config
    home.shellAliases = {};

    xdg.enable = true;

    programs.zsh = {
      enable = true;
      dotDir = ".config/zsh";
    };

    programs.direnv = {
      enable = true;
      nix-direnv.enable = true;
    };

    home.file = {
      ".config/zsh" = {
        source = ./_zsh;
        recursive = true;
      };

      # "zsh/extra.zshrc".text = let
      #   aliasLines = lib.mapAttrsToList (n: v: "alias ${n}=\"${v}\"") cfg.aliases;
      # in ''
      #   # This file was autogenerated, do not edit it!
      #   ${lib.concatStringsSep "\n" aliasLines}
      #   ${lib.concatMapStrings (path: "source '${path}'\n") cfg.rcFiles}
      #   ${cfg.rcInit}
      # '';

      # "zsh/extra.zshenv".text = ''
      #   # This file is autogenerated, do not edit it!
      #   ${lib.concatMapStrings (path: "source '${path}'\n") cfg.envFiles}
      #   ${cfg.envInit}
      # '';

      ".config/zsh/extra.zshenv".text = "";

      ".config/zsh/extra.zshrc".text = ''
        source ${./_zsh}/prompt.zsh
        _cache tmuxifier init -
        eval "$(direnv hook zsh)"

        alias vim=nvim
        alias top=btm
      '';
    };
  };
}
# # This file was autogenerated, do not edit it!
# alias k="kubectl"
# source '/nix/store/yg00rzmcnxn0rk92pdcszskzc66y56kp-prompt.zsh'
# source '/home/jboyens/.config/dotfiles/config/tmux/aliases.zsh'
# source '/home/jboyens/.config/dotfiles/config/git/aliases.zsh'
# source '/home/jboyens/.config/dotfiles/config/docker/aliases.zsh'
# source '/home/jboyens/.config/dotfiles/config/emacs/aliases.zsh'
# _cache bw completion --shell zsh; compdef _bw bw;
# _cache tmuxifier init -
# eval "$(direnv hook zsh)"
# [ "$TERM" = alacritty ] && export TERM=xterm-256color

